const assert=require('node:assert/strict');
const fs=require('node:fs');
const root=process.argv[2]||'.';
const html=fs.readFileSync(root+'/index.html','utf8');
const app=fs.readFileSync(root+'/src/app.js','utf8');
const refresh=fs.readFileSync(root+'/supabase/functions/yt1988-refresh/index.ts','utf8');
const gateway=fs.readFileSync(root+'/supabase/functions/yt1988/index.ts','utf8');
const cacheMigration=fs.readFileSync(root+'/supabase/migrations/20260926050000_channel_snapshot_cache.sql','utf8');
const refreshConfigMigration=fs.readFileSync(root+'/supabase/migrations/20260926061000_configurable_feed_refresh.sql','utf8');

assert.match(html,/id="yt-player"/);
assert.match(html,/id="nativePlayer"/);
assert.match(html,/id="topicChips"/);
assert.match(html,/youtube\.com\/iframe_api/);
assert.doesNotMatch(html,/id="pipBtn"/);
assert.match(html,/id="lockBtn"/);
assert.match(app,/new YT\.Player/);
assert.match(app,/youtube-nocookie\.com/);
assert.doesNotMatch(app,/videoMediaUrl\(id\)/);
assert.doesNotMatch(app,/mainVideo/);
assert.match(app,/local\.media\(id,"audio"\)/);
assert.match(app,/function setupMediaSession\(/);
assert.match(app,/const LIVE_SOURCE_SCOPE="live"/);
assert.match(app,/const LATEST_SOURCE_SCOPE="latest"/);
assert.match(app,/const WEEK_SOURCE_SCOPE="week"/);
assert.match(app,/defaultLabel:"Ngày"[\s\S]*profile:"day"/);
assert.match(app,/defaultLabel:"Tuần"[\s\S]*profile:"week"/);
assert.match(app,/key:"news"[\s\S]*defaultLabel:"Khám phá"[\s\S]*profile:"explore"/);
assert.match(app,/key:"economy"[\s\S]*defaultLabel:"Review"[\s\S]*profile:"review"/);
assert.match(app,/key:"law"[\s\S]*defaultLabel:"Hài"[\s\S]*profile:"comedy"/);
assert.match(app,/key:"film"[\s\S]*defaultLabel:"Phim ngắn"[\s\S]*profile:"short_film"/);
assert.match(app,/key:"music"[\s\S]*defaultLabel:"Nhạc"[\s\S]*profile:"music"/);
assert.match(app,/key:"tech"[\s\S]*defaultLabel:"Công nghệ"[\s\S]*profile:"technology"/);
assert.match(app,/key:"sports"[\s\S]*defaultLabel:"Thể thao"[\s\S]*profile:"sports"/);
assert.match(app,/key:"entertainment"[\s\S]*defaultLabel:"Showbiz"[\s\S]*profile:"showbiz"/);
assert.match(app,/const MANAGED_SOURCE_SCOPES=new Set\(SOURCE_SCOPE_DEFINITIONS\.map/);
assert.match(app,/review:profile==="review"/);
assert.match(app,/contentProfile:context\.profile/);
assert.match(app,/selectedSourceFeed\([\s\S]*LATEST_SOURCE_SCOPE/);
assert.match(app,/selectedSourceFeed\([\s\S]*WEEK_SOURCE_SCOPE/);
assert.match(app,/state\.activeFeed===LIVE_SOURCE_SCOPE\)return LIVE_SOURCE_SCOPE/);
assert.doesNotMatch(app,/\{key:"general",label:"Mới nhất\/Tuần này"\}/);
assert.match(app,/const SOURCE_FEED_AUTO_REFRESH_MS=30\*1000/);
assert.match(app,/function queuePackageUpload\(_snapshotName=""\)\{[\s\S]*return Promise\.resolve\(false\)/);
assert.match(app,/Client is download-only:[\s\S]*never back-filled/);
assert.match(app,/Read last complete server package immediately[\s\S]*never crawl YouTube here/);
assert.match(app,/async function buildSourceFeedSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*readFeedCache/);
assert.match(app,/async function buildCategorySourceSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*instantCategoryRows/);
assert.match(app,/watchPlaybackVisible\(\)\|\|\s*state\.activeFeed!==name/);
assert.match(app,/function syncServerPackagesOnResume\(\)/);
assert.match(app,/window\.addEventListener\("pageshow",syncServerPackagesOnResume/);
assert.match(app,/window\.addEventListener\("focus",syncServerPackagesOnResume/);
assert.match(refresh,/DEFAULT_SCOPE_INTERVAL_MINUTES/);
assert.match(refresh,/yt1988_refresh_config/);
assert.match(refresh,/channelRecheckMs/);
assert.match(refresh,/yt1988_channel_cache/);
assert.match(refresh,/function relativeAgeMs\(/);
assert.match(refresh,/catastrophic_package_shrink/);
assert.match(refresh,/yt1988_queue_refresh/);
assert.match(refresh,/MAX_CHANNEL_FETCHES_PER_RUN=30/);
assert.match(gateway,/async function pipedChannel\(/);
assert.match(gateway,/if \(!channelRows\(data\)\.length\) continue/);
assert.match(gateway,/async function youtubeRssChannel\(/);
assert.match(gateway,/youtube\.com\/feeds\/videos\.xml/);
assert.match(gateway,/source: "youtube-rss"/);
assert.match(cacheMigration,/create table if not exists public\.yt1988_channel_cache/);
assert.match(cacheMigration,/create or replace function public\.yt1988_finish_refresh_v2/);
assert.match(refreshConfigMigration,/create table if not exists public\.yt1988_refresh_config/);
assert.match(refreshConfigMigration,/interval_minutes integer not null default 10/);
assert.match(refreshConfigMigration,/body := jsonb_build_object\('scopes',to_jsonb\(due_scopes\)\)/);

console.log('integration-shape: source/player assertions passed');
