const assert=require('node:assert/strict');
const fs=require('node:fs');
const root=process.argv[2]||'.';
const html=fs.readFileSync(root+'/index.html','utf8');
const app=fs.readFileSync(root+'/src/app.js','utf8');
const sw=fs.readFileSync(root+'/sw.js','utf8');
const refresh=fs.readFileSync(root+'/supabase/functions/yt1988-refresh/index.ts','utf8');
const gateway=fs.readFileSync(root+'/supabase/functions/yt1988/index.ts','utf8');
const cacheMigration=fs.readFileSync(root+'/supabase/migrations/20260926050000_channel_snapshot_cache.sql','utf8');
const refreshConfigMigration=fs.readFileSync(root+'/supabase/migrations/20260926061000_configurable_feed_refresh.sql','utf8');
const allMigrations=fs.readdirSync(root+'/supabase/migrations')
  .filter(name=>name.endsWith('.sql'))
  .map(name=>fs.readFileSync(root+'/supabase/migrations/'+name,'utf8'))
  .join('\n');

assert.match(html,/id="yt-player"/);
assert.match(html,/id="nativePlayer"/);
assert.match(html,/id="topicChips"/);
assert.match(html,/youtube\.com\/iframe_api/);
assert.doesNotMatch(html,/id="pipBtn"/);
assert.match(html,/id="lockBtn"/);
assert.match(app,/new YT\.Player/);
assert.match(app,/youtube-nocookie\.com/);
assert.doesNotMatch(app,/videoMediaUrl\(id\)/);
assert.doesNotMatch(app,/mainVideo/);
assert.match(app,/local\.media\(id,"audio"\)/);
assert.match(app,/function setupMediaSession\(/);
assert.match(app,/const LIVE_SOURCE_SCOPE="live"/);
assert.match(app,/const LATEST_SOURCE_SCOPE="latest"/);
assert.match(app,/const WEEK_SOURCE_SCOPE="week"/);
assert.match(app,/defaultLabel:"Ngày"[\s\S]*profile:"day"/);
assert.match(app,/defaultLabel:"Tuần"[\s\S]*profile:"week"/);
assert.match(app,/key:"news"[\s\S]*defaultLabel:"Khám phá"[\s\S]*profile:"explore"/);
assert.match(app,/key:"economy"[\s\S]*defaultLabel:"Review"[\s\S]*profile:"review"/);
assert.match(app,/key:"law"[\s\S]*defaultLabel:"Hài"[\s\S]*profile:"comedy"/);
assert.match(app,/key:"film"[\s\S]*defaultLabel:"Phim ngắn"[\s\S]*profile:"short_film"/);
assert.match(app,/key:"music"[\s\S]*defaultLabel:"Nhạc"[\s\S]*profile:"music"/);
assert.match(app,/key:"tech"[\s\S]*defaultLabel:"Công nghệ"[\s\S]*profile:"technology"/);
assert.match(app,/key:"sports"[\s\S]*defaultLabel:"Thể thao"[\s\S]*profile:"sports"/);
assert.match(app,/key:"entertainment"[\s\S]*defaultLabel:"Showbiz"[\s\S]*profile:"showbiz"/);
assert.match(app,/const MANAGED_SOURCE_SCOPES=new Set\(SOURCE_SCOPE_DEFINITIONS\.map/);
assert.match(app,/review:profile==="review"/);
assert.match(app,/contentProfile:context\.profile/);
assert.match(app,/selectedSourceFeed\([\s\S]*LATEST_SOURCE_SCOPE/);
assert.match(app,/selectedSourceFeed\([\s\S]*WEEK_SOURCE_SCOPE/);
assert.match(app,/state\.activeFeed===LIVE_SOURCE_SCOPE\)return LIVE_SOURCE_SCOPE/);
assert.doesNotMatch(app,/\{key:"general",label:"Mới nhất\/Tuần này"\}/);
assert.match(app,/const SOURCE_FEED_AUTO_REFRESH_MS=30\*1000/);
assert.match(app,/function queuePackageUpload\(_snapshotName=""\)\{[\s\S]*return Promise\.resolve\(false\)/);
assert.match(app,/Client is download-only:[\s\S]*never back-filled/);
assert.match(app,/Read last complete server package immediately[\s\S]*never crawl YouTube here/);
assert.match(app,/async function buildSourceFeedSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*readFeedCache/);
assert.match(app,/async function buildCategorySourceSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*instantCategoryRows/);
assert.match(app,/watchPlaybackVisible\(\)\|\|\s*state\.activeFeed!==name/);
assert.match(app,/function syncServerPackagesOnResume\(\)/);
assert.match(app,/window\.addEventListener\("pageshow",syncServerPackagesOnResume/);
assert.match(app,/window\.addEventListener\("focus",syncServerPackagesOnResume/);
assert.match(app,/LOCAL_DATA_SCHEMA_VERSION="320"/);
assert.match(app,/function clearVolatileLocalData\(\)/);
assert.match(app,/async function clearLocalDataAndReload\(\)/);
assert.match(app,/sourceDataResetBtn\?\.addEventListener\("click"/);
assert.match(html,/id="sourceDataResetBtn"/);
assert.match(html,/id="liveKeywordTools"/);
assert.match(html,/id="liveKeywordInput"/);
assert.match(html,/id="liveKeywordChips"/);
assert.match(app,/const LIVE_KEYWORDS_STATE_KEY="__live_keywords"/);
assert.match(app,/const LIVE_KEYWORDS_PENDING_KEY="1988-live-keywords-pending-v1"/);
assert.match(app,/let stateSyncRevision=0/);
assert.match(app,/function persistPendingLiveKeywords\(/);
assert.match(app,/function recoverPendingLiveKeywords\(/);
assert.match(app,/function queueLiveKeywordServerSave\(/);
assert.match(app,/function flushPendingServerStateOnPageHide\(/);
assert.match(app,/stateSyncRevision>pushedRevision/);
assert.match(app,/clearPendingLiveKeywordsThrough\(pushedRevision\)/);
assert.match(app,/window\.addEventListener\("pagehide",flushPendingServerStateOnPageHide/);
assert.match(app,/function renderLiveKeywordTools\(/);
assert.match(app,/directCount\+" chọn · "/);
assert.match(app,/inheritedCount\+" đã có · "/);
assert.match(app,/nguồn dùng cho Live/);
assert.match(app,/function liveKeywordBlockedClient\(/);
assert.match(app,/function liveEffectiveBlockedSet\(/);
assert.match(app,/function liveEffectiveSelectedSet\(/);
assert.match(app,/function liveSourceManagerState\(/);
assert.match(app,/inheritedSelected/);
assert.match(app,/"Đã có"/);
assert.match(app,/scope===LIVE_SOURCE_SCOPE\?liveEffectiveSelectedSet\(\):selectedSetForScope\(scope\)/);
assert.match(app,/sourceManageGroup===LIVE_SOURCE_SCOPE/);
assert.match(app,/LIVE_KEYWORDS_STATE_KEY/);
assert.match(html,/sw\.js\?v=320/);
assert.match(sw,/1988-main-watch-browse-v320/);
assert.match(refresh,/DEFAULT_SCOPE_INTERVAL_MINUTES/);
assert.match(refresh,/yt1988_refresh_config/);
assert.match(refresh,/channelRecheckMs/);
assert.match(refresh,/yt1988_channel_cache/);
assert.match(refresh,/function relativeAgeMs\(/);
assert.match(refresh,/catastrophic_package_shrink/);
assert.match(refresh,/yt1988_queue_refresh/);
assert.match(refresh,/MAX_CHANNEL_FETCHES_PER_RUN=30/);
assert.match(refresh,/function normalizeLiveText\(/);
assert.match(refresh,/function liveKeywordBlocked\(/);
assert.match(refresh,/yt1988_live_keywords/);
assert.match(refresh,/function strongFreshLiveSignal\(/);
assert.match(refresh,/Number\(row\?\.duration\)<0&&Number\(row\?\.uploaded\)===-1/);
assert.match(refresh,/async function selectedSourceLiveNow\(/);
assert.match(refresh,/youtube\.com\/channel\/["']?\+encodeURIComponent\(id\)\+["']?\/live/);
assert.match(refresh,/method:"HEAD"/);
assert.match(refresh,/redirect:"follow"/);
assert.match(refresh,/"videoViewCountRenderer"[\s\S]*?"isLive"/);
assert.match(refresh,/const allBlockedLiveSourceIds=new Set/);
assert.match(refresh,/const generalBlockedIds=new Set<string>\(\)/);
assert.match(refresh,/if\(scope===["']general["']\)/);
assert.match(refresh,/new Set<string>\(generalBlockedIds\)/);
assert.match(refresh,/const explicitLiveIds=new Set/);
assert.match(refresh,/const inheritedLiveIds=new Set/);
assert.match(refresh,/const selectedLiveSources=\[\.\.\.liveSourceById\.values\(\)\]/);
assert.match(refresh,/SCOPES\.flatMap\(\(scope\)=>selectedByScope\.get\(scope\)\|\|\[\]\)/);
assert.match(refresh,/async function discoverGlobalLiveCandidates\(/);
assert.match(refresh,/blockedSourceIds:Set<string>/);
assert.match(refresh,/selectedSourceIds:Set<string>/);
assert.match(refresh,/selected:dedupeRows\(selected\)/);
assert.match(refresh,/const LIVE_SEARCH_QUERIES=\[/);
assert.match(refresh,/const LIVE_PIPELINE_VERSION=["']live-v20["']/);
assert.match(refresh,/meta\.kind===["']live["']\?LIVE_PIPELINE_VERSION/);
assert.match(refresh,/"trực tiếp"/);
assert.match(refresh,/"livestream việt nam"/);
assert.match(refresh,/mapLimit\(LIVE_SEARCH_QUERIES,4/);
assert.doesNotMatch(refresh,/"search_next&q="/);
assert.match(refresh,/_liveOrigin:"search"/);
assert.match(refresh,/_liveOrigin:"source"/);
assert.match(refresh,/const discovery=await discoverGlobalLiveCandidates/);
assert.match(refresh,/allBlockedLiveSourceIds,[\s\S]*allSelectedLiveSourceIds,[\s\S]*liveKeywords/);
assert.match(refresh,/const selectedFromSearch=/);
assert.match(refresh,/const selectedSeenIds=new Set/);
assert.match(refresh,/const selectedToCheck=selectedLiveSources\.filter/);
assert.match(refresh,/mapLimit\(selectedToCheck,6/);
assert.match(refresh,/const row=await selectedSourceLiveNow\(source\)/);
assert.match(refresh,/const selectedLiveRows=dedupeRows\(\[/);
assert.match(refresh,/verifiedLiveRowsCache=dedupeRows\(\[/);
assert.doesNotMatch(refresh,/verifyLiveRows/);
assert.doesNotMatch(refresh,/verifyLiveCandidate/);
assert.doesNotMatch(refresh,/searchSelectedSourceLiveCandidates/);
assert.doesNotMatch(refresh,/youtubeRssLiveCandidates/);
assert.doesNotMatch(refresh,/Promise\.all\(\[\s*selectedDiscoveryPromise,globalDiscoveryPromise\s*\]\)/);
assert.match(refresh,/meta\.kind!==["']live["']&&raw\.length>=4/);
assert.match(refresh,/if\(!packaged\.length&&scope!==["']live["']\)/);
assert.match(gateway,/async function pipedChannel\(/);
assert.match(gateway,/if \(!channelRows\(data\)\.length\) continue/);
assert.match(gateway,/async function youtubeRssChannel\(/);
assert.match(gateway,/youtube\.com\/feeds\/videos\.xml/);
assert.match(gateway,/source: "youtube-rss"/);
assert.match(cacheMigration,/create table if not exists public\.yt1988_channel_cache/);
assert.match(cacheMigration,/create or replace function public\.yt1988_finish_refresh_v2/);
assert.match(refreshConfigMigration,/create table if not exists public\.yt1988_refresh_config/);
assert.match(refreshConfigMigration,/interval_minutes integer not null default 10/);
assert.match(refreshConfigMigration,/body := jsonb_build_object\('scopes',to_jsonb\(due_scopes\)\)/);
assert.match(allMigrations,/create table if not exists public\.yt1988_live_keywords/);
assert.match(allMigrations,/__live_keywords/);
assert.match(allMigrations,/yt1988_sync_live_keywords_from_state/);
assert.match(allMigrations,/after insert or update of state on public\.yt1988_user_state/);
assert.match(allMigrations,/v_keyword_norm text/);
assert.match(allMigrations,/left\(v_keyword_norm,80\)/);
assert.match(allMigrations,/old_live_keywords/);
assert.match(allMigrations,/old_live_keywords is distinct from raw_keywords/);
assert.match(allMigrations,/jsonb_build_object\('scopes',jsonb_build_array\('live'\)\)/);
assert.match(allMigrations,/jsonb_build_object\('scopes',jsonb_build_array\('live'\)\)/);

console.log('integration-shape: source/player assertions passed');
