const assert=require('node:assert/strict');
const fs=require('node:fs');
const root=process.argv[2]||'.';
const html=fs.readFileSync(root+'/index.html','utf8');
const app=fs.readFileSync(root+'/src/app.js','utf8');
const mediaMeta=fs.readFileSync(root+'/src/media-meta.js','utf8');
const ytLocal=fs.readFileSync(root+'/src/yt-local.js','utf8');
const sw=fs.readFileSync(root+'/sw.js','utf8');
const style=fs.readFileSync(root+'/src/style.css','utf8');
const refresh=fs.readFileSync(root+'/supabase/functions/yt1988-refresh/index.ts','utf8');
const gateway=fs.readFileSync(root+'/supabase/functions/yt1988/index.ts','utf8');
const stateApi=fs.readFileSync(root+'/supabase/functions/yt1988-state/index.ts','utf8');
const packageApi=fs.readFileSync(root+'/supabase/functions/yt1988-packages/index.ts','utf8');
const hashtagMigration=fs.readFileSync(root+'/supabase/migrations/20260926090000_dynamic_hashtag_feeds.sql','utf8');
const fairRefreshMigration=fs.readFileSync(root+'/supabase/migrations/20260926173000_fair_hashtag_refresh.sql','utf8');
const cacheMigration=fs.readFileSync(root+'/supabase/migrations/20260926050000_channel_snapshot_cache.sql','utf8');
const refreshConfigMigration=fs.readFileSync(root+'/supabase/migrations/20260926061000_configurable_feed_refresh.sql','utf8');
const allMigrations=fs.readdirSync(root+'/supabase/migrations')
  .filter(name=>name.endsWith('.sql'))
  .map(name=>fs.readFileSync(root+'/supabase/migrations/'+name,'utf8'))
  .join('\n');

const simpleProduction=
  /id=["']videoFrame["']/.test(html) &&
  /yt1988-video-meta/.test(html) &&
  /new YTApi\.Player\(["']videoFrame["']/.test(html);

if(simpleProduction){
  // Production v2: one YT.Player surface. MAIN / PiP / 2-column are only
  // presentation modes; media aspect/kind is owned by the current video id.
  assert.match(html,/id=["']videoFrame["']/);
  assert.match(html,/new YTApi\.Player\(["']videoFrame["']/);
  assert.match(html,/youtube-nocookie\.com/);
  assert.match(html,/function syncCurrentKindFromYoutubePlayer\(/);
  assert.match(html,/loadedId\|\|loadedId!==expectedId/);
  assert.match(html,/videoContentRect/);
  assert.match(html,/const VIDEO_META_URL=.*yt1988-video-meta/);
  assert.match(html,/function fetchServerAspects\(/);
  assert.match(html,/function primeMediaAspects\(/);
  assert.match(html,/function reportVerifiedAspect\(/);
  assert.match(html,/method:["']POST["']/);
  assert.match(html,/function playVideoId\(/);
  assert.match(html,/playerApi\.loadVideoById\(id\)/);
  assert.match(html,/if\(ytPlayer&&ytPlayerReady\)/);
  assert.match(html,/ytPlayer\.loadVideoById\(id\)/);
  assert.match(html,/void ensureYoutubePlayer\(\);/);
  assert.match(html,/onError\(event\)/);
  assert.match(html,/startNativeVideoFallback\(id,code\)/);
  assert.match(html,/native-video-fallback/);
  assert.match(html,/YT1988_API\?\.mediaUrl\?\.\(id,["']video["']\)/);
  assert.doesNotMatch(html,/cueVideoById/);
  assert.doesNotMatch(html,/thumbnailContentAspect|detectPillarboxFromImage|primeCardPortraitNow/);
  assert.match(html,/const PACKAGE_SYNC_URL=.*yt1988-packages/);
  assert.match(html,/YT1988_API\.search\(raw,["']videos["']\)/);
  assert.match(html,/player\.classList\.toggle\(["']pip["'],!!floating\)/);
  assert.match(html,/player\.classList\.add\(["']pip["']\)/);
  assert.match(html,/player\.classList\.remove\(["']pip["']\)/);
  assert.match(html,/function layoutFeedMasonry\(/);
  assert.match(html,/rows\.classList\.add\(["']masonry-active["']\)/);
  assert.match(html,/grid-auto-flow:row dense/);
  assert.match(html,/const cardGap=32/);
  assert.match(html,/root\.classList\.toggle\(["']two-col["'],two\)/);
  assert.match(html,/current\?\.kind===["']portrait["']/);
  assert.match(html,/navigator\.serviceWorker/);
  assert.match(sw,/1988-simple-media-v24/);
  assert.match(sw,/\.\/index\.html/);
  console.log('integration-shape: simple production media contract passed');
  process.exit(0);
}

assert.match(html,/id="yt-player"/);
assert.match(html,/id="nativePlayer"/);
assert.match(html,/id="topicChips"/);
assert.match(html,/youtube\.com\/iframe_api/);
assert.doesNotMatch(html,/id="pipBtn"/);
assert.match(html,/id="lockBtn"/);
assert.match(app,/new YT\.Player/);
assert.match(app,/youtube-nocookie\.com/);
assert.doesNotMatch(app,/videoMediaUrl\(id\)/);
assert.doesNotMatch(app,/mainVideo/);
assert.match(html,/youtube\.com\/iframe_api" defer/);
assert.match(html,/<meta name="referrer" content="strict-origin-when-cross-origin">/);
assert.match(html,/id="sourceVideoFrame"[\s\S]{0,180}referrerpolicy="strict-origin-when-cross-origin"/);
assert.match(app,/const YOUTUBE_IFRAME_ERROR_INFO=\{/);
assert.match(app,/2:\{[\s\S]{0,180}definitive:true[\s\S]{0,120}nativeFallback:false/);
assert.match(app,/5:\{[\s\S]{0,180}nativeFallback:true/);
assert.match(app,/100:\{[\s\S]{0,180}definitive:true[\s\S]{0,120}nativeFallback:false/);
assert.match(app,/101:\{[\s\S]{0,180}definitive:true[\s\S]{0,120}nativeFallback:true/);
assert.match(app,/150:\{[\s\S]{0,180}definitive:true[\s\S]{0,120}nativeFallback:true/);
assert.match(app,/153:\{[\s\S]{0,180}definitive:false[\s\S]{0,120}nativeFallback:true/);
assert.match(app,/function handleYoutubeIframeError\(/);
assert.match(app,/fallbackIframeVideoToNative\(id,errorCode,\{[\s\S]{0,220}advanceOnFailure:true/);
assert.match(app,/function handleYoutubeAutoplayBlocked\(/);
assert.match(app,/onAutoplayBlocked\(\)[\s\S]{0,100}handleYoutubeAutoplayBlocked\(\)/);
assert.match(app,/widget_referrer:location\.href/);
assert.match(app,/iframe\.referrerPolicy="strict-origin-when-cross-origin"/);
assert.match(app,/ytWait>100[\s\S]{0,700}fallbackIframeVideoToNative\(id,0,/);
assert.match(ytLocal,/const EMBED_PLAYBACK_LIVE_OFFLINE_TTL=60\*1000/);
assert.match(ytLocal,/function embedPlaybackTtl\(/);
assert.match(ytLocal,/status===['"]LIVE_STREAM_OFFLINE['"]\)return EMBED_PLAYBACK_LIVE_OFFLINE_TTL/);
assert.match(ytLocal,/const ttl=embedPlaybackTtl\(result\)/);

assert.match(app,/if\(window\.YT&&typeof YT\.Player==="function"\)\{/);
assert.match(app,/function createFloatingSwipeZone\(/);
assert.doesNotMatch(app,/frame\.append\(zone,overlay\);/);
assert.match(app,/function closeFloatingPipAndExitPlayback\(/);
assert.match(app,/closeFloatingPipAndExitPlayback\(\)/);
assert.doesNotMatch(app,/frame&&!frame\.querySelector\("\.watch-swipe-zone"\)/);
assert.doesNotMatch(style,/Full mobile Watch owns the touch surface too/);
assert.match(app,/function hideFloatOverlayControls\(/);
assert.match(app,/function setupWatchMinimizeGesture\(/);
assert.doesNotMatch(app,/watchPipEnterPageY|setupMainWatchGestureSurface|watchMainGestureSurface/);
assert.doesNotMatch(style,/Single mobile Watch scroller v445|Mobile main-player swipe bridge v447|Reference PiP geometry \+ controls v444/);
assert.match(app,/avatar\.replaceChildren\(img\)/);
assert.match(app,/selectedVideoAvatarFallback\.hidden=!!channelAvatar/);
assert.match(style,/grid-template-rows:\s*var\(--watch-stage-h,56\.25vw\)\s*auto\s*auto!important/);
assert.match(style,/\.selected-video-info\{\s*grid-row:2!important/);
assert.match(style,/\.feed-section\{\s*grid-row:3!important/);
assert.match(app,/state\.intentPlay=true;[\s\S]{0,140}showFloatOverlayControls\(frame,2600\)/);
assert.match(style,/float-controls-suppressed[\s\S]{0,180}visibility:hidden!important[\s\S]{0,120}transition:none!important/);
assert.match(app,/float-controls-suppressed/);
assert.doesNotMatch(app,/data-float-overlay="fullscreen"/);
assert.doesNotMatch(app,/function fullscreenFloatingPlayer\(/);
assert.doesNotMatch(app,/pipFullscreenPending|pipFullscreenRestore/);
assert.match(app,/function compactPipAnchorFromBox\(/);
assert.match(app,/function currentCompactPipAnchor\(/);
assert.match(app,/startFloatMove\(event,frame\)/);
assert.match(app,/function syncWatchPipToFirstVideo\(/);
assert.match(style,/PiP interaction ownership v439/);
assert.match(style,/Simple PiP controls \+ touch drag v441/);
assert.doesNotMatch(style,/Fullscreen exit ownership v440/);
assert.match(style,/pointer-events:none!important/);
assert.match(app,/local\.media\(id,"audio"\)/);
assert.match(app,/function setupMediaSession\(/);
assert.match(app,/const LIVE_SOURCE_SCOPE="live"/);
assert.match(app,/const LATEST_SOURCE_SCOPE="latest"/);
assert.match(app,/const WEEK_SOURCE_SCOPE="week"/);
assert.match(app,/const SYSTEM_SOURCE_SCOPE_DEFINITIONS=\[/);
assert.match(app,/defaultLabel:"Ngày"[\s\S]*profile:"day"/);
assert.match(app,/defaultLabel:"Tuần"[\s\S]*profile:"week"/);
assert.match(app,/function normalizeHashtagDefinitions\(/);
assert.match(app,/function rebuildSourceScopeRegistry\(/);
assert.match(app,/profile:"hashtag"/);
assert.match(app,/function setHashtagDefinitions\(/);
assert.match(app,/async function createHashtag\(/);
assert.match(app,/op:"create_hashtag"/);
assert.match(app,/op:"rename_hashtag"/);
assert.match(app,/data-hashtag-add/);
assert.doesNotMatch(app,/key:"news"[\s\S]*profile:"explore"/);
assert.doesNotMatch(app,/key:"economy"[\s\S]*profile:"review"/);
assert.match(app,/MANAGED_SOURCE_SCOPES=new Set\(SOURCE_SCOPE_DEFINITIONS\.map/);
assert.match(app,/selectedSourceFeed\([\s\S]*LATEST_SOURCE_SCOPE/);
assert.match(app,/selectedSourceFeed\([\s\S]*WEEK_SOURCE_SCOPE/);
assert.match(app,/state\.activeFeed===LIVE_SOURCE_SCOPE\)return LIVE_SOURCE_SCOPE/);
assert.doesNotMatch(app,/\{key:"general",label:"Mới nhất\/Tuần này"\}/);
assert.match(app,/const SOURCE_FEED_AUTO_REFRESH_MS=30\*1000/);
assert.match(app,/function queuePackageUpload\(_snapshotName=""\)\{[\s\S]*return Promise\.resolve\(false\)/);
assert.match(app,/Package viewing is independent from source-management availability/);
assert.match(app,/Keep the last complete local reserve[\s\S]*browser never deletes packaged data/);
assert.match(app,/async function buildSourceFeedSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*readFeedCache/);
assert.match(app,/async function buildCategorySourceSnapshot\([\s\S]*hydrateServerPackages\(\{force:true\}\)[\s\S]*instantCategoryRows/);
assert.match(app,/watchPlaybackVisible\(\)\|\|\s*state\.activeFeed!==name/);
assert.match(app,/function syncServerPackagesOnResume\(\)/);
assert.match(app,/window\.addEventListener\("pageshow",syncServerPackagesOnResume/);
assert.match(app,/window\.addEventListener\("focus",syncServerPackagesOnResume/);
assert.match(app,/LOCAL_DATA_SCHEMA_VERSION="337"/);
assert.match(app,/function clearVolatileLocalData\(\)/);
assert.doesNotMatch(app,/Chưa có video phù hợp trong tab này/);
assert.doesNotMatch(app,/Chưa có video phù hợp trong mục này/);
assert.match(app,/async function clearLocalDataAndReload\(\)/);
assert.match(app,/sourceDataResetBtn\?\.addEventListener\("click"/);
assert.match(html,/id="sourceDataResetBtn"/);
assert.match(html,/id="liveKeywordTools"/);
assert.match(html,/id="liveKeywordInput"/);
assert.match(html,/id="liveKeywordChips"/);
assert.match(app,/const LIVE_KEYWORDS_STATE_KEY="__live_keywords"/);
assert.match(app,/const LIVE_KEYWORDS_PENDING_KEY="1988-live-keywords-pending-v1"/);
assert.match(app,/let stateSyncRevision=0/);
assert.match(app,/function persistPendingLiveKeywords\(/);
assert.match(app,/function recoverPendingLiveKeywords\(/);
assert.match(app,/function queueLiveKeywordServerSave\(/);
assert.match(app,/function flushPendingServerStateOnPageHide\(/);
assert.match(app,/stateSyncRevision>pushedRevision/);
assert.match(app,/clearPendingLiveKeywordsThrough\(pushedRevision\)/);
assert.match(app,/window\.addEventListener\("pagehide",flushPendingServerStateOnPageHide/);
assert.match(app,/function renderLiveKeywordTools\(/);
assert.match(app,/function isTooShortVideo\(row=\{\}\)/);
assert.match(app,/function shouldHideVideo\(row=\{\}\)/);
assert.match(app,/EN_TITLE_WORDS/);
assert.match(app,/VI_TITLE_WORDS/);
assert.match(app,/seconds>0&&seconds<=60/);
assert.match(app,/#shorts\?/);
assert.match(app,/type===["']short["']\|\|type===["']shorts["']/);
assert.match(app,/trustedPackage=options\.trustedPackage===true/);
assert.match(refresh,/function isTooShortVideo\(row:any\)/);
assert.match(refresh,/function youtubePlayerMetaFromResponse\(data:any\)/);
assert.match(refresh,/async function youtubePlayerMetadata\(id:string\)/);
assert.match(refresh,/function exactSearchVideoMeta\(data:any,id:string\)/);
assert.match(refresh,/async function youtubeSearchVideoMetadata/);
assert.match(refresh,/youtubeSearchVideoMetadata\(supabaseUrl,serviceKey,candidate\.id\)/);
assert.match(refresh,/data\?\.name\|\|data\?\.title/);
assert.match(refresh,/const sourceMetaUpdates=\[\.\.\.channelMeta\.values\(\)\]/);
assert.match(refresh,/yt1988_source_state\?profile_key=eq\./);
assert.match(refresh,/function youtubeShortsPageSignal\(html:string,id:string\)/);
assert.match(refresh,/async function youtubeShortsMembership\(id:string\)/);
assert.match(refresh,/const needShort=!shortCheckedAt/);
assert.match(refresh,/youtubeShortsMembership\(candidate\.id\)/);
assert.match(refresh,/const NON_LIVE_VERIFY_BATCH=48/);
assert.match(refresh,/const currentPackageVideoIds=new Set<string>\(\)/);
assert.match(refresh,/inCurrentPackage:currentPackageVideoIds\.has\(id\)/);
assert.match(refresh,/Number\(b\.inCurrentPackage\)-Number\(a\.inCurrentPackage\)/);
assert.match(refresh,/const canonicalSource=channelMeta\.get\(source\.id\)\|\|source/);
assert.match(refresh,/!!validChannelDisplayName\(r\?\._sourceName\|\|r\?\.uploaderName\|\|r\?\.uploader\|\|""\)/);
assert.doesNotMatch(refresh,/candidate\.needDuration&&Number\(searchMeta\?\.duration\)<=0[\s\S]{0,120}youtubePlayerMetadata\(candidate\.id\)/);

assert.match(refresh,/isShort:meta\.isShort===true\|\|row\?\.isShort===true/);
assert.match(refresh,/empty_candidate_kept_previous/);
assert.doesNotMatch(app,/LOCAL_VOLATILE_PREFIXES=\[[\s\S]{0,600}"1988-tab-snapshot-"/);
assert.match(app,/The browser never deletes packaged data/);
assert.match(app,/const legacyHash=snapshotRowsHashV330\(items,sourceSig\)/);
assert.match(app,/serverHash:expectedHash/);
assert.match(app,/knownLocalHashes=new Set/);
assert.match(refresh,/Number\(r\?\._shortCheckedAt\)>0/);
assert.doesNotMatch(refresh,/reason:["']waiting_non_live_verification["']/);
assert.match(app,/return row&&Array\.isArray\(row\.items\)\?row\.items\.slice\(\):\[\]/);
assert.match(app,/renderCards\(state\.feedRows,\{trustedPackage:true\}\)/);
assert.match(refresh,/const verificationCandidates:any\[\]=\[\]/);
assert.match(refresh,/const verificationScopeChannelIds=new Set<string>\(\)/);
assert.match(refresh,/resolverVersion<3/);
assert.match(refresh,/_durationResolverVersion:meta\.durationCheckedAt\?3/);
assert.match(refresh,/exact video-ID search is the[\s\S]{0,120}duration source/i);
assert.match(refresh,/verificationCandidates\.slice\(0,NON_LIVE_VERIFY_BATCH\),8/);
assert.match(refresh,/_durationCheckedAt/);
assert.match(refresh,/_shortCheckedAt/);
assert.match(app,/String\(durationSeconds\(row\)\|\|0\)/);
assert.match(app,/function syncStableCardBadge\(/);
assert.match(mediaMeta,/youtubeWideFallback[\s\S]{0,160}mqdefault\.jpg/);
assert.match(mediaMeta,/function knownYoutubePaddedThumb\(/);
assert.match(app,/const YOUTUBE_THUMBNAIL_UPGRADE_LIMIT=12/);
assert.match(app,/function supplementalSeekEnabled\(/);
assert.match(app,/function applyWatchProgressAccent\(/);
assert.match(app,/applyWatchProgressAccent\(art,state\.currentId\)/);
assert.match(app,/dataset\.thumbFallback="2"/);
assert.match(app,/function paintVisibleRowSourceAvatars\(rows=\[\]\)/);
assert.match(app,/controls:1/);
assert.doesNotMatch(app,/controls:controlsMode/);
assert.match(app,/function ensureUnifiedMediaChrome\(\)/);
assert.match(html,/id=["\']watchMediaBar["\'][^>]*class=["\']watch-media-bar["\']/);
assert.doesNotMatch(html,/data-watch-media=["\']play["\']/);
assert.doesNotMatch(html,/data-watch-media=["\']mute["\']/);
assert.doesNotMatch(html,/data-watch-media=["\']fullscreen["\']/);
assert.doesNotMatch(html,/class=["\']watch-media-time["\']/);
assert.doesNotMatch(app,/className=["\']watch-media-chrome["\']/);
assert.doesNotMatch(app,/className=["\']watch-media-tap-surface["\']/);
assert.doesNotMatch(style,/watch-media-top-mask/);
assert.doesNotMatch(style,/watch-media-bottom-mask/);
assert.match(style,/THIN SEPARATE MEDIA BAR v476/);
assert.match(style,/\.watch-media-bar[\s\S]{0,700}height:28px/);
assert.match(style,/\.watch-media-progress-track[\s\S]{0,220}height:2px/);
assert.match(style,/html\[data-player-ui-mode=["\']pip["\']\] \.watch-media-bar[\s\S]{0,80}display:none/);
assert.match(app,/watch-media-progress/);
assert.match(app,/function showUnifiedMediaChrome\(/);
assert.match(app,/function syncUnifiedMediaProgress\(/);
assert.match(app,/function seekUnifiedMediaFromClientX\(/);
assert.match(app,/let watchMediaSeekResume=false/);
assert.match(app,/let watchMediaSeekTarget=null/);
assert.match(app,/let watchMediaSeekSettlingUntil=0/);
assert.match(app,/function commitUnifiedMediaSeek\(/);
assert.match(app,/unifiedMediaDuration\(\)\|\|durationSeconds\(state\.currentMeta\|\|\{\}\)/);
assert.match(app,/watchMediaSeekResume=!!\(state\.intentPlay\|\|state\.videoPlaying\)/);
assert.match(app,/watchMediaSeekTarget=ratio/);
assert.match(app,/commitUnifiedMediaSeek\(frame\)/);
assert.match(app,/const seekPause=[\s\S]{0,160}Date\.now\(\)<watchMediaSeekSettlingUntil/);
assert.match(app,/function resumeUnifiedMediaAfterSeek\(/);
assert.match(app,/function toggleUnifiedMediaPlayback\(/);
assert.match(app,/return ["']pip["']/);
assert.match(app,/return ["']main["']/);
assert.doesNotMatch(app,/return watchAutoPipViewport\(\)\?["']minimal["']:["']full["']/);
assert.doesNotMatch(app,/function rebuildYoutubeIframeForControls\(/);
assert.doesNotMatch(app,/class=["']float-overlay-play["']/);
assert.match(style,/THIN SEPARATE MEDIA BAR v476/);
assert.match(style,/\.watch-media-progress/);
assert.match(app,/let ytPlayerHost=\$\("#yt-player"\)/);
assert.match(app,/function desiredYoutubeIframeControlsMode\(/);
assert.doesNotMatch(app,/function rebuildYoutubeIframeForControls\(/);
assert.doesNotMatch(app,/function syncYoutubeIframeControlsForViewport\(\)/);
assert.doesNotMatch(app,/state\.player\.destroy\?\.\(\)/);
assert.doesNotMatch(app,/youtubeIframeControlsRestore/);
assert.match(app,/function currentPlayerUiMode\(\)/);
assert.match(app,/return ["']pip["']/);
assert.doesNotMatch(app,/return watchAutoPipViewport\(\)\?["']minimal["']:["']full["']/);
assert.match(app,/function syncPlayerUiMode\(/);
assert.match(app,/state\.watchMinimized\s*&&\s*!watchAutoPipViewport\(\)[\s\S]{0,180}setWatchMinimized\(false,\{preserveScroll:true\}\)/);
assert.match(app,/function mobileBrowserViewport\(/);
assert.match(app,/function watchSideMediaLayout\(/);
assert.match(app,/function watchInlineMediaLayout\(/);
assert.match(app,/const WATCH_MEDIA_MAIN_TOP=["']main-top["']/);
assert.match(app,/const WATCH_MEDIA_MAIN_SIDE=["']main-side["']/);
assert.match(app,/const WATCH_MEDIA_PIP=["']pip["']/);
assert.match(app,/function desiredWatchMediaPlacement\(/);
assert.match(app,/function syncWatchMediaPlacement\(/);
assert.match(app,/function queueWatchMediaPlacement\(/);
assert.doesNotMatch(app,/let pipGeometryRaf=0/);
assert.match(app,/syncMobileInlinePlayerViewport\(\);[\s\S]{0,120}releaseWatchMediaSlot\(\)/);
assert.match(app,/min-width:960px/);
assert.match(app,/return watchInlineMediaLayout\(\)/);
assert.match(app,/state\.watchMinimized[\s\S]{0,180}watchSideMediaLayout\(\)[\s\S]{0,220}setWatchMinimized\(false,\{preserveScroll:true\}\)/);
assert.match(app,/const uiMode=currentPlayerUiMode\(\)/);
assert.match(app,/syncNativePlayerControls\(\)/);
assert.match(app,/syncYoutubeIframeControlsForUiMode\(uiMode\)/);
assert.match(app,/function syncMainMinimalControls\([\s\S]{0,120}uiMode/);
assert.match(app,/window\.addEventListener\("resize",\(\)=>\{\s*syncPlayerUiMode\(\)/);
assert.match(app,/visualViewport\?\.addEventListener\?\.\("resize",\(\)=>\{\s*syncPlayerUiMode\(\)/);
assert.match(app,/orientationchange[\s\S]{0,140}syncPlayerUiMode\(\)/);
assert.doesNotMatch(app,/window\.addEventListener\("resize",\(\)=>\{[\s\S]{0,220}syncYoutubeIframeControlsForViewport\(\)/);
assert.match(app,/function ensureMainMinimalControls\(\)/);
assert.match(app,/function toggleMainMinimalPlayback\(/);
assert.match(app,/function toggleMainMinimalMute\(/);
assert.match(app,/function toggleMainMinimalFullscreen\(/);
assert.match(app,/nativePlayer\.controls=true/);
assert.match(app,/preserveExistingOrder:refreshExisting/);
assert.match(app,/function currentFloatingAspect\(/);
assert.match(app,/watchRestoreUntil:0/);
assert.match(app,/Date\.now\(\)>=Number\(state\.watchRestoreUntil\|\|0\)/);
assert.match(app,/zone\.addEventListener\("pointerdown"[\s\S]{0,120}startFloatMove\(event,frame\)/);
assert.doesNotMatch(app,/document\.addEventListener\("touchstart",event=>\{\s*lastTouchAt=Date\.now\(\)/);
assert.match(app,/syncFloatingPlayerViewport\(frame,\{settle:true\}\)/);
assert.match(app,/state\.floatBox=\{[\s\S]{0,220}ratio\s*\n?\s*\};/);
assert.doesNotMatch(style,/transition:transform \.16s ease,width \.16s ease,height \.16s ease/);
assert.match(style,/--main-page-bg:#0f0f0f/);
assert.match(app,/function desktopHoverAccentEnabled\(/);
assert.match(app,/feed\?\.addEventListener\("pointerover"/);
assert.match(app,/primeDesktopCardHoverColors\(\)/);
assert.match(style,/Desktop full-card colour hover v403/);
assert.match(style,/@media \(hover:hover\) and \(pointer:fine\) and \(min-width:760px\)/);
assert.match(style,/\.feed>\.card\.desktop-accent-hover::before/);
assert.match(style,/\.feed>\.card \.thumb-wrap\{[\s\S]*border-radius:13px!important;[\s\S]*overflow:hidden!important;/);
assert.match(style,/\.feed>\.card \.thumb-wrap img\{[\s\S]*border-radius:13px!important;/);
assert.match(style,/\.feed-section\{[\s\S]*padding-left:12px!important;[\s\S]*padding-right:12px!important;/);
assert.match(style,/scrollbar-gutter:stable/);
assert.match(style,/var\(--desktop-card-accent,rgb\(38,38,40\)\)/);
assert.match(app,/const boost=value=>/);
assert.match(style,/inset:-10px -9px -12px/);
assert.match(style,/\.feed>\.card\.desktop-accent-hover \.card-copy[\s\S]*background:transparent!important/);
assert.doesNotMatch(style,/html\.desktop-hover-accent\.watch-browse \.player-card/);
assert.doesNotMatch(app,/root\.classList\.add\("desktop-hover-accent"\)/);
assert.match(style,/scrollbar-color:var\(--main-scroll-thumb\) var\(--main-page-bg\)/);
assert.match(style,/\.feed>\.card \.card-copy[\s\S]*background:var\(--main-page-bg\)!important/);
assert.doesNotMatch(app,/currentThumbWrap\.querySelectorAll\("\\.duration,\\.live-badge"\)\.forEach\(node=>node\.remove\(\)\)/);
assert.match(app,/menu\.style\.visibility="hidden"/);
assert.match(app,/menu\.style\.visibility="visible"/);
assert.match(refresh,/String\(durationSeconds\(row\)\|\|0\)/);
assert.match(refresh,/VI_TITLE_WORDS_STRONG/);
assert.match(refresh,/function dedupePackageRows\(rows:any\[\]\)/);
assert.match(refresh,/function cleanSourceTitle\(value:any,sourceName:any\)/);
assert.match(refresh,/function packageCoreTitle\(row:any\)/);
assert.match(refresh,/function obviousNonNewsForNewsScope\(row:any\)/);
assert.match(refresh,/meta\.kind===["']live["']\?dedupeRows\(raw\):dedupePackageRows\(raw\)/);
assert.doesNotMatch(refresh,/non_live_verification_pending/);
assert.match(refresh,/durationSeconds\(r\)>60/);

assert.match(refresh,/duration>0&&duration<=60/);
assert.match(refresh,/#shorts\?/);
assert.match(refresh,/type===["']short["']\|\|type===["']shorts["']/);
assert.match(refresh,/NON_LIVE_PIPELINE_VERSION=["']non-live-v9["']/);
assert.match(refresh,/!isTooShortVideo\(r\)/);
assert.match(app,/function isBlockedMusicTabVideo\(scope="",row=\{\}\)/);
assert.match(app,/\\b\(\?:beat\|kara\|karaoke\)\\b/);
assert.match(refresh,/function isBlockedMusicTabVideo\(meta:any=\{\},row:any=\{\}\)/);
assert.match(refresh,/meta\.kind===["']content["']\)raw=raw\.filter\(\(r:any\)=>!isBlockedMusicTabVideo\(meta,r\)\)/);
assert.match(app,/directCount\+" chọn · "/);
assert.match(app,/inheritedCount\+" đã có · "/);
assert.match(app,/nguồn dùng cho Live/);
assert.match(app,/function liveKeywordBlockedClient\(/);
assert.match(app,/function liveEffectiveBlockedSet\(/);
assert.match(app,/function liveEffectiveSelectedSet\(/);
assert.match(app,/function liveSourceManagerState\(/);
assert.match(app,/inheritedSelected/);
assert.match(app,/"Đã có"/);
assert.match(app,/scope===LIVE_SOURCE_SCOPE\?liveEffectiveSelectedSet\(\):selectedSetForScope\(scope\)/);
assert.match(app,/sourceManageGroup===LIVE_SOURCE_SCOPE/);
assert.match(app,/LIVE_KEYWORDS_STATE_KEY/);
const swVersion=html.match(/sw\.js\?v=([A-Za-z0-9._-]+)/)?.[1]||"";
assert.ok(swVersion,"index.html must version sw.js");
assert.ok(sw.includes("1988-main-watch-browse-v"+swVersion),"sw.js cache version must match index.html");
assert.match(refresh,/DEFAULT_SYSTEM_INTERVAL_MINUTES/);
assert.match(refresh,/DEFAULT_HASHTAG_INTERVAL_MINUTES=10/);
assert.match(refresh,/yt1988_hashtags/);
assert.match(refresh,/profile:"hashtag"/);
assert.match(refresh,/reason:"no_selected_sources"/);
assert.match(refresh,/yt1988_refresh_config/);
assert.match(refresh,/channelRecheckMs/);
assert.match(refresh,/yt1988_channel_cache/);
assert.match(refresh,/function relativeAgeMs\(/);

assert.match(refresh,/yt1988_queue_refresh/);
assert.match(refresh,/MAX_CHANNEL_FETCHES_PER_RUN=12/);
assert.match(refresh,/MAX_SCOPES_PER_RUN=2/);
assert.match(refresh,/LIVE_SELECTED_SOURCES_PER_RUN=32/);
assert.match(refresh,/function normalizeLiveText\(/);
assert.match(refresh,/function liveKeywordBlocked\(/);
assert.match(refresh,/yt1988_live_keywords/);
assert.match(refresh,/function strongFreshLiveSignal\(/);
assert.match(refresh,/return isLive\(row\)/);
assert.match(refresh,/async function selectedSourceLiveNow\(source:any,candidates:any\[\]=\[\]\)/);
assert.match(refresh,/youtube\.com\/channel\/["']?\+encodeURIComponent\(id\)\+["']?\/live/);
assert.match(refresh,/method:"GET"/);
assert.match(refresh,/await probe\.body\?\.cancel\(\)/);
assert.match(refresh,/async function youtubePlayerIsLive\(/);
assert.match(refresh,/is_viewed_live/);
assert.match(refresh,/LIVE_SELECTED_CANDIDATES_PER_SOURCE=2/);
assert.match(refresh,/const liveCandidateRowsById=new Map<string,any\[\]>\(\)/);
assert.match(refresh,/redirect:"follow"/);
assert.match(refresh,/data\?\.videoDetails\?\.isLive===true/);
assert.match(refresh,/const allBlockedLiveSourceIds=new Set/);
assert.match(refresh,/const liveBlockedIds=blockedByScope\.get\("live"\)/);
assert.match(refresh,/if\(scope===["']general["']\)/);
assert.match(refresh,/new Set<string>\(liveBlockedIds\)/);
assert.match(refresh,/const explicitLiveIds=new Set/);
assert.match(refresh,/const inheritedLiveIds=new Set/);
assert.match(refresh,/const selectedLiveSources=\[\.\.\.liveSourceById\.values\(\)\]/);
assert.match(refresh,/SCOPES\.flatMap\(\(scope\)=>selectedByScope\.get\(scope\)\|\|\[\]\)/);
assert.match(refresh,/async function discoverGlobalLiveCandidates\(/);
assert.match(refresh,/blockedSourceIds:Set<string>/);
assert.match(refresh,/selectedSourceIds:Set<string>/);
assert.match(refresh,/selected:dedupeRows\(selected\)/);
assert.match(refresh,/const LIVE_SEARCH_QUERIES=\[/);
assert.match(refresh,/const LIVE_PIPELINE_VERSION=["']live-v31["']/);
assert.match(refresh,/meta\.kind===["']live["']\?LIVE_PIPELINE_VERSION/);
assert.match(refresh,/"trực tiếp"/);
assert.match(refresh,/"livestream việt nam"/);
assert.match(refresh,/mapLimit\(LIVE_SEARCH_QUERIES,4/);
assert.doesNotMatch(refresh,/"search_next&q="/);
assert.match(refresh,/_liveOrigin:"search"/);
assert.match(refresh,/_liveOrigin:"source"/);
assert.match(refresh,/const discovery=await discoverGlobalLiveCandidates/);
assert.match(refresh,/allBlockedLiveSourceIds,[\s\S]*allSelectedLiveSourceIds,[\s\S]*liveKeywords/);
assert.match(refresh,/const selectedFromSearch=/);
assert.match(refresh,/const selectedSeenIds=new Set/);
assert.match(refresh,/const remainingSelected=selectedLiveSources\.filter/);
assert.match(refresh,/mapLimit\(selectedToCheck,6/);
assert.match(refresh,/const row=await selectedSourceLiveNow\([\s\S]*source,[\s\S]*liveCandidateRowsById\.get\(source\.id\)\|\|\[\][\s\S]*\)/);
assert.match(refresh,/const selectedLiveRows=dedupeRows\(\[/);
assert.match(refresh,/verifiedLiveRowsCache=dedupeRows\(\[/);
assert.doesNotMatch(refresh,/verifyLiveRows/);
assert.doesNotMatch(refresh,/verifyLiveCandidate/);
assert.doesNotMatch(refresh,/searchSelectedSourceLiveCandidates/);
assert.doesNotMatch(refresh,/youtubeRssLiveCandidates/);
assert.doesNotMatch(refresh,/Promise\.all\(\[\s*selectedDiscoveryPromise,globalDiscoveryPromise\s*\]\)/);


assert.match(stateApi,/create_hashtag/);
assert.match(stateApi,/rename_hashtag/);
assert.match(stateApi,/reorder_hashtags/);
assert.match(stateApi,/set_hashtag_enabled/);
assert.match(stateApi,/sourceScopeVersion: 5/);
assert.match(stateApi,/Full profile saves are presentation-only/);
assert.match(packageApi,/HASHTAG_ID_RE/);
assert.match(packageApi,/yt1988_hashtags/);
assert.match(hashtagMigration,/create table if not exists public\.yt1988_hashtags/);
assert.match(hashtagMigration,/hash_001/);
assert.match(hashtagMigration,/hash_008/);
assert.match(hashtagMigration,/scope in \('news','economy','law','film','music','tech','sports','entertainment'\)/);
assert.match(hashtagMigration,/zero selected sources|status='selected'/i);
assert.match(fairRefreshMigration,/guarantee one due hashtag per tick/i);
assert.match(fairRefreshMigration,/package_updated_at asc nulls first/);
assert.match(html,/id="sourceGroupAdd"/);
assert.match(html,/← Quay lại/);
assert.match(app,/sourceStatusSection\("Gợi ý nguồn"/);
assert.match(gateway,/function mergeYoutubeOriginalTitles\(/);
assert.match(gateway,/const rssPromise = youtubeRssChannel\(id\)/);
assert.match(gateway,/title: String\(original\?\.title/);
assert.match(gateway,/const result = await pipedChannel\(id\)/);
assert.match(gateway,/async function pipedChannel\(/);
assert.match(gateway,/if \(!channelRows\(data\)\.length\) continue/);
assert.match(gateway,/async function youtubeRssChannel\(/);
assert.match(gateway,/youtube\.com\/feeds\/videos\.xml/);
assert.match(gateway,/source: "youtube-rss"/);
assert.match(cacheMigration,/create table if not exists public\.yt1988_channel_cache/);
assert.match(cacheMigration,/create or replace function public\.yt1988_finish_refresh_v2/);
assert.match(refreshConfigMigration,/create table if not exists public\.yt1988_refresh_config/);
assert.match(refreshConfigMigration,/interval_minutes integer not null default 10/);
assert.match(refreshConfigMigration,/body := jsonb_build_object\('scopes',to_jsonb\(due_scopes\)\)/);
assert.match(allMigrations,/create table if not exists public\.yt1988_live_keywords/);
assert.match(allMigrations,/__live_keywords/);
assert.match(allMigrations,/yt1988_sync_live_keywords_from_state/);
assert.match(allMigrations,/after insert or update of state on public\.yt1988_user_state/);
assert.match(allMigrations,/v_keyword_norm text/);
assert.match(allMigrations,/left\(v_keyword_norm,80\)/);
assert.match(allMigrations,/old_live_keywords/);
assert.match(allMigrations,/old_live_keywords is distinct from raw_keywords/);
assert.match(allMigrations,/jsonb_build_object\('scopes',jsonb_build_array\('live'\)\)/);
assert.match(allMigrations,/jsonb_build_object\('scopes',jsonb_build_array\('live'\)\)/);

console.log('integration-shape: source/player assertions passed');

assert.doesNotMatch(style,/WATCH SOURCE RAIL CLEANUP v477/);
assert.match(style,/html\.watch-browse:not\(\.watch-search-open\):not\(\.watch-search-results\)\{[\s\S]{0,120}--watch-source-row-h:0px!important/);
assert.match(style,/html\.watch-browse:not\(\.watch-search-open\):not\(\.watch-search-results\) \.header-nav\{[\s\S]{0,120}display:none!important/);

assert.match(app,/function freezeWatchMediaSlot\(\)[\s\S]{0,1400}--watch-inline-slot-h["'],slotHeight\+["']px["']/);
assert.match(app,/anchor\.style\.height=slotHeight\+["']px["']/);
assert.match(app,/function animateWatchPlayerFlip\(/);
assert.match(app,/animateWatchPlayerFlip\(mainRect,watchPlayerRect\(\)\)/);
assert.match(app,/animateWatchPlayerFlip\(pipRect,watchPlayerRect\(\)\)/);
assert.doesNotMatch(app,/function freezeWatchMediaSlot\(\)[\s\S]{0,1200}--watch-inline-slot-art["'],['"]url/);
assert.match(style,/WATCH GRID \+ PIP SLOT v478/);
assert.match(style,/@media\(max-width:720px\)[\s\S]{0,1200}grid-template-rows:[\s\S]{0,240}var\(--watch-media-bar-h\)[\s\S]{0,120}auto[\s\S]{0,120}minmax\(0,1fr\)/);
assert.match(style,/\.selected-video-info\{[\s\S]{0,120}grid-row:2!important/);
assert.match(style,/\.feed-section\{[\s\S]{0,120}grid-row:3!important/);
assert.match(style,/\.header-nav\{[\s\S]{0,120}display:none!important/);

assert.match(style,/REMOVE WATCH AMBIENT v479/);
assert.match(style,/html\.watch-browse body::before\{[\s\S]{0,240}display:none!important/);
assert.match(style,/html\.watch-browse body::before\{[\s\S]{0,420}background:none!important/);

assert.match(style,/COLLAPSE HOME HIDDEN HEADER GAP v480/);
assert.match(style,/home-header-hidden \.app-header\{[\s\S]{0,220}height:calc\(var\(--nav-row-h\) \+ var\(--safe-top\)\)!important/);
assert.match(style,/home-header-hidden \.app-shell\{[\s\S]{0,160}padding-top:calc\(var\(--nav-row-h\) \+ var\(--safe-top\) \+ 6px\)!important/);

assert.match(app,/const PIP_SIZE_STEPS=\[1,1\.25,1\.5,1\.8,3\]/);
assert.match(app,/function pipSizeKey\(/);
assert.match(app,/return "full"/);


assert.doesNotMatch(app,/class=["']float-media-controls["']/);
assert.doesNotMatch(app,/data-float-overlay=["']play["']/);
assert.doesNotMatch(app,/data-float-overlay=["']mute["']/);
assert.doesNotMatch(app,/class=["']float-media-progress["']/);
assert.match(app,/function syncFloatMediaControls\(/);
assert.match(app,/function bindFloatMediaSeek\(/);

assert.match(app,/float-size-small/);
assert.match(app,/float-size-medium/);
assert.match(app,/float-size-mid/);
assert.match(app,/float-size-large/);
assert.match(app,/float-size-full/);
assert.match(app,/function floatingViewportRect\(/);
assert.match(app,/const anchor=currentCompactPipAnchor\(\)/);
assert.match(app,/if\(pipSizeKey\(scale\)===["']full["']\)\{[\s\S]{0,260}let width=maxWidth;[\s\S]{0,180}height=width\/ratio;[\s\S]{0,180}if\(height>maxHeight\)/);
assert.match(app,/height=maxHeight;[\s\S]{0,80}width=height\*ratio/);
assert.match(app,/object-fit["'],["']contain["']/);
assert.doesNotMatch(app,/fullCoverVideoAspect/);
assert.doesNotMatch(app,/pipFullViewportRect/);
assert.doesNotMatch(app,/fullCover\?/);
assert.doesNotMatch(style,/PIP FIVE SIZES \+ MEDIA v481/);
assert.doesNotMatch(style,/\.float-size-full[\s\S]{0,220}border-radius:0!important/);

assert.match(style,/SIMPLE VIDEO PROGRESS v482/);
assert.match(style,/--watch-media-bar-h:6px/);
assert.match(style,/background:var\(--video-progress-accent,#8b8cff\)!important/);
assert.match(app,/--video-progress-accent/);
assert.match(app,/className=["']float-media-progress["']/);
assert.doesNotMatch(app,/float-media-play/);
assert.doesNotMatch(app,/float-media-mute/);
assert.match(app,/frame\.append\(zone,overlay,progress\)/);
assert.match(style,/\.float-media-progress[\s\S]{0,500}bottom:0!important/);

assert.match(app,/function youtubeCinematicPalette\(/);
assert.match(app,/const YOUTUBE_CINEMATIC_OPACITY=\.4/);
assert.match(app,/const YOUTUBE_CINEMATIC_BASE=\[15,15,15\]/);
assert.match(app,/function paintCardCinematicColor\(/);
assert.match(app,/--card-cinematic-surface/);
assert.match(app,/--card-cinematic-accent/);
assert.match(app,/function applyWatchProgressAccent\([\s\S]{0,900}youtubeCinematicPalette\(art\)/);
assert.doesNotMatch(app,/frame\.style\.setProperty\("--pip-button-bg"/);
assert.match(app,/base\*\(1-YOUTUBE_CINEMATIC_OPACITY\)\+accent\[i\]\*YOUTUBE_CINEMATIC_OPACITY/);
assert.match(app,/Sampled colour[\s\S]{0,180}not painted behind each card/);
assert.doesNotMatch(app,/const color=await averageThumbTint\(art\)/);
assert.match(style,/UNIFIED VIDEO ACCENT/);
assert.match(style,/YOUTUBE-STYLE NEUTRAL CARDS \+ MINIPLAYER/);
assert.match(style,/background:rgba\(0,0,0,\.50\)!important/);
assert.match(style,/width:40px!important/);
assert.doesNotMatch(app,/habitAspect/);
assert.match(app,/state\.videoAspectHabitPrimed=false/);
assert.match(app,/function cleanupFloatingForBrowse\([\s\S]{0,900}releaseWatchMediaSlot\(\)/);
assert.match(app,/if\(active&&!state\.watchMinimized\)cleanupFloatingForBrowse\(\)/);
assert.match(app,/loadedId&&loadedId!==expectedId/);
assert.match(app,/\[90,260,700,1400,2600,4500\]\.forEach/);
assert.match(style,/YOUTUBE CINEMATIC COLOR v483/);
assert.match(style,/\.card-copy[\s\S]{0,220}--card-cinematic-surface/);
assert.match(style,/height:4px!important/);
assert.match(style,/--video-progress-accent/);

assert.match(app,/visualViewport/);
assert.match(app,/state\.videoAspectVerified/);
assert.match(app,/function syncMaxPipToVisualViewport\(/);
assert.match(app,/placeCompactWatchPip\(frame,\{preservePosition:true\}\)/);
assert.match(style,/PIP MAX ASPECT FIT v485/);
assert.doesNotMatch(style,/PIP FULL VISUAL COVER/);
assert.match(style,/\.float-size-full \.float-overlay-scale[\s\S]{0,220}top:8px!important/);
assert.match(style,/\.float-size-full \.float-overlay-close[\s\S]{0,220}top:8px!important/);

assert.match(app,/const PIP_STANDARD_ASPECTS=\[/);
assert.match(app,/16\/9,9\/16/);
assert.match(app,/const PIP_ASPECT_SNAP_TOLERANCE=\.05/);
assert.match(app,/return nearestDelta<=PIP_ASPECT_SNAP_TOLERANCE\?nearest:ratio/);
assert.match(app,/function explicitVideoAspect\([\s\S]{0,260}return validPipAspect\(ratio\)/);
assert.match(app,/playerSection\.style\.setProperty\("aspect-ratio",String\(ratio\),"important"\)/);
assert.match(app,/frame\.style\.setProperty\("aspect-ratio",String\(ratio\),"important"\)/);
assert.match(app,/function youtubeFloatingRenderBox\(/);
assert.match(app,/const minEmbedSide=200/);
assert.match(app,/minEmbedSide\/visualWidth/);
assert.match(app,/minEmbedSide\/visualHeight/);
assert.match(app,/iframe\.setAttribute\("width",String\(Math\.ceil\(renderBox\.layoutWidth\)\)\)/);
assert.match(app,/iframe\.setAttribute\("height",String\(Math\.ceil\(renderBox\.layoutHeight\)\)\)/);
assert.match(app,/onPlaybackQualityChange\(event\)/);
assert.doesNotMatch(app,/frameWidth\+2/);
assert.doesNotMatch(app,/frameHeight\+2/);
assert.doesNotMatch(app,/mediaLeft=-1/);
assert.doesNotMatch(app,/mediaTop=-1/);
assert.match(style,/CANONICAL PIP MEDIA SURFACE v486/);
assert.match(style,/PIP CLEAN BLACK SURFACE v487/);
assert.match(style,/\.floating-iframe::before\{[\s\S]{0,220}display:none!important[\s\S]{0,220}filter:none!important/);

assert.match(style,/\.floating-iframe iframe,[\s\S]{0,260}width:100%!important[\s\S]{0,120}height:100%!important/);

