'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const demo=fs.readFileSync('tiktok-live-cloud-demo.html','utf8');

assert.match(demo,/TikTok LIVE Direct Demo/);
assert.match(demo,/Danh sách video/);
assert.match(demo,/EDGE\+"\/lookup\?user="/);
assert.match(demo,/LIBRARY\+"\/tiktok\/library"/);
assert.match(demo,/async function loadLive\(h\)/);
assert.match(demo,/let currentLiveState=null/);
assert.match(demo,/id="channelsBox"/);
assert.match(demo,/id="liveBox"/);
assert.match(demo,/replayLive\(\)/);
assert.match(demo,/const LIVE_LINK_TTL_MS=45_000/);
assert.match(demo,/const VOD_LINK_TTL_MS=90_000/);
assert.match(demo,/function liveStateFresh\(\)/);
assert.match(demo,/async function refreshLiveState\(h\)/);
assert.match(demo,/Date\.now\(\)-currentLiveStateAt<LIVE_LINK_TTL_MS/);
assert.match(demo,/video\.onerror=null/);
assert.match(demo,/grid-template-columns:minmax\(220px,260px\) minmax\(260px,330px\) minmax\(0,1fr\)/);
assert.match(demo,/grid-template-areas:"source videos player"/);
assert.match(demo,/height:clamp\(430px,72vh,720px\)/);
assert.match(demo,/object-fit:contain/);
assert.match(demo,/async function loadChannelLibrary\(h\)/);
assert.match(demo,/endpoint\.searchParams\.set\("user",h\)/);
assert.match(demo,/Promise\.allSettled\(\[liveTask,videoTask\]\)/);
assert.match(demo,/renderVideos\(videos\)/);
assert.doesNotMatch(demo,/target="_blank"/);
assert.match(demo,/data-video-i/);
assert.match(demo,/async function playChannelVideo\(row,index=currentVideos\.indexOf\(row\)\)/);
assert.doesNotMatch(demo,/\/tiktok\/video-direct\?user=/);
assert.match(demo,/async function resolveTikwmVideo\(row\)/);
assert.match(demo,/async function getWarmTikwmLink\(row\)/);
assert.match(demo,/function warmVideoLink\(row\)/);
assert.match(demo,/pointerenter/);
assert.match(demo,/pointerdown/);
assert.match(demo,/touchstart/);
assert.match(demo,/id="prevMedia"/);
assert.match(demo,/id="nextMedia"/);
assert.match(demo,/id="playerShape"/);
assert.match(demo,/shape-portrait/);
assert.match(demo,/shape-landscape/);
assert.match(demo,/function applyMediaShape\(width,height\)/);
assert.match(demo,/video\.addEventListener\("loadedmetadata"/);
assert.match(demo,/const sessionChannels=new Map\(\)/);
assert.match(demo,/async function loadInitialCatalog\(\)/);
assert.match(demo,/LIBRARY\+"\/tiktok\/library\?t="/);
assert.match(demo,/EDGE\+"\/state\?t="/);
assert.match(demo,/latestVideos\.sort/);
assert.match(demo,/function videoThumb\(row\)/);
assert.match(demo,/loading="lazy"/);
assert.match(demo,/const sessionLiveStates=new Map\(\)/);
assert.match(demo,/function moveVideo\(delta\)/);
assert.match(demo,/playerStage\.addEventListener\("wheel"/);
assert.match(demo,/playerStage\.addEventListener\("touchend"/);
assert.match(demo,/link\.rel="preconnect"/);
assert.match(demo,/video\.preload="metadata"/);
assert.match(demo,/vodLinkCache\.clear\(\)/);
assert.match(demo,/www\.tikwm\.com\/api\/\?url=/);
assert.match(demo,/body\?\.hdplay\|\|body\?\.play/);
assert.match(demo,/async function resolveBhwaVideo\(row\)/);
assert.match(demo,/downloader-api\.bhwa233\.com\/api\/parse\?url=/);
assert.match(demo,/one988-tiktok-session\.onrender\.com/);
assert.match(demo,/TikWM HD/);
assert.match(demo,/BHWA/);

console.log('tiktok demo: canonical one-channel library + Cloudflare LIVE + direct browser media');

assert.match(demo,/let currentChannelLibrary=null/);
assert.match(demo,/currentChannelLibrary\?\.profile/);
assert.match(demo,/result\.count\+\" video thư viện\"/);
