'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const demo=fs.readFileSync('tiktok-live-cloud-demo.html','utf8');
assert.match(demo,/id="input"/);
assert.match(demo,/tu\.thuong_lay_minh_1/);
assert.match(demo,/\/refresh\?user=/);
assert.match(demo,/\/tiktok\/live-now/);
assert.match(demo,/\/tiktok\/channel-videos\?refresh=0&user=/);
assert.match(demo,/\/tiktok\/video-stream\?user=/);
assert.match(demo,/source=\\"\+encodeURIComponent\(source\)/);
assert.match(demo,/mpegts\.createPlayer\(\{type:"flv",isLive:true/);
assert.doesNotMatch(demo,/\/sweep/);
assert.doesNotMatch(demo,/resolveTikTokLiveEdge/);
assert.doesNotMatch(demo,/video-refresh-all/);
console.log('tiktok targeted live + five videos demo contract ok');
