'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const demo=fs.readFileSync('tiktok-live-cloud-demo.html','utf8');
assert.match(demo,/id="input"/);
assert.match(demo,/tu\.thuong_lay_minh_1/);
assert.match(demo,/\/tiktok\/profile\?user=/);
assert.match(demo,/limit=5/);
assert.match(demo,/profile\?\.live/);
assert.match(demo,/profile\?\.videos/);
assert.match(demo,/\/tiktok\/video-stream\?user=/);
assert.match(demo,/mpegts\.createPlayer/);
assert.doesNotMatch(demo,/\/sweep/);
assert.doesNotMatch(demo,/\/tiktok\/live-now/);
assert.doesNotMatch(demo,/\/refresh\?user=/);
console.log('tiktok one-link live + five videos demo contract ok');
