const assert=require('node:assert/strict');
const fs=require('node:fs');

const worker=fs.readFileSync('cloudflare/tiktok-live-state/worker.js','utf8');

assert.match(worker,/const VIDEO_SNAPSHOT_KEY = "tiktok:video:fingerprint";/);
assert.match(worker,/const VIDEO_BATCH_SIZE = 6;/);
assert.match(worker,/async function selectedChannels\(\)/);
assert.match(worker,/secUid: String\(row\?\.secUid \|\| ""\)\.trim\(\)/);
assert.match(worker,/latestVideoId: normalizeVideoId\(row\?\.latestVideoId \|\| ""\)/);
assert.match(worker,/async function checkTikTokVideoFingerprint\(channel\)/);
assert.match(worker,/api\/post\/item_list\//);
assert.match(worker,/endpoint\.searchParams\.set\("count", "1"\)/);
assert.match(worker,/async function wakeRenderVideoRefresh\(handle\)/);
assert.match(worker,/endpoint\.searchParams\.set\("full", "1"\)/);
assert.match(worker,/First observation is only a baseline/);
assert.match(worker,/Wake at most one channel per minute/);
assert.match(worker,/const video = await videoFingerprintSweep\(env, selectedRows\);/);
assert.doesNotMatch(worker,/selectedHandles\(\)/);
assert.match(worker,/const TIKTOK_VOD_SOURCE_VERSION = "avc4";/);
assert.match(worker,/const preferredIsAvc=\/h264\|avc\//);
assert.match(worker,/preferredIsAvc\?\(preferred\?\.urls\|\|\[\]\):\[\]/);
assert.match(worker,/probe\?\.avc1&&row\?\.probe\?\.mp4a/);
assert.match(worker,/probe\?\.avc1/);
assert.match(worker,/const audioOnly=audioCodec&&!videoCodec/);
assert.match(worker,/function tiktokMediaResponseLooksUsable\(response\)/);
assert.match(worker,/response\.status===206&&contentRange/);
assert.match(worker,/for\(const target of candidates\)/);
assert.match(worker,/source\.name==="native"[\s\S]{0,220}fetchTikTokNativeMediaTarget/);
assert.match(worker,/const walk=\(v,depth=0,inheritedId=""\)=>/);
assert.match(worker,/const ownerId=localId\|\|String\(inheritedId\|\|""\)/);
assert.match(worker,/const relevant=!wantedId\|\|!ownerId\|\|ownerId===wantedId/);
assert.match(worker,/walk\(x,depth\+1,ownerId\)/);
assert.match(worker,/const VOD_RESOLVER_POOL=\["tikwm","tdown","musicaldown","tikdown","ttdownloader"\]/);
assert.match(worker,/async function resolveMusicalDownVideoSource/);
assert.match(worker,/async function resolveTikdownOrgVideoSource/);
assert.match(worker,/async function resolveTTDownloaderVideoSource/);
assert.match(worker,/async function resolveTiklyDownVideoSource/);
assert.match(worker,/async function resolveDouyinWtfVideoSource/);
assert.match(worker,/vodSourceOrder\(preferred,id\)/);
assert.doesNotMatch(worker,/for \(let attempt = 0; attempt < 2; attempt\+\+\)/);
assert.match(worker,/Never call the same provider twice in the/);

console.log('tiktok-edge-video-fingerprint-contract: assertions passed');
